# Generated by Django 4.1.2 on 2022-10-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField(default=None)),
                ('img_idx', models.IntegerField(default=None)),
                ('image', models.ImageField(default=None, upload_to='img/')),
            ],
        ),
    ]
