# Generated by Django 4.1.2 on 2022-10-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='img_bytes',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
    ]
