# Generated by Django 4.1.2 on 2022-10-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_image', '0002_remove_generatedimage_img_bytes_generatedimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='img_url',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
