# Generated by Django 4.1.2 on 2022-10-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save_image', '0004_generatedimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='img_url',
        ),
    ]
