# Generated by Django 4.1.2 on 2022-10-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='name',
            field=models.TextField(default='hoge', verbose_name='name'),
        ),
    ]
