# Generated by Django 4.1.2 on 2022-10-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=128, unique=True)),
                ('prompt', models.TextField(blank=True, default='')),
                ('state', models.IntegerField(choices=[(0, 'inprocessing'), (1, 'completed'), (-1, 'desabled')], default=0)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('queue_length', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='images/result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_image', to='aiconapi.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='input_tags',
            field=models.ManyToManyField(to='aiconapi.tag'),
        ),
    ]
