# Generated by Django 4.1.2 on 2022-10-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='images/result')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aiconapi.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='input_tags',
            field=models.ManyToManyField(to='aiconapi.tag'),
        ),
    ]
