# Generated by Django 4.1.2 on 2022-10-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiconapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(default='dummy', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
