# Generated by Django 4.1.2 on 2022-10-18 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aiconapi', '0002_reservation_reservation_id_alter_reservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_checked',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='queue_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_image', to='aiconapi.reservation'),
        ),
    ]
