# Generated by Django 4.1.2 on 2022-10-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiconapi', '0003_reservation_completed_reservation_last_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
