# Generated by Django 4.1.2 on 2022-10-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiconapi', '0005_alter_generatedimage_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_image', to='aiconapi.reservation'),
        ),
    ]
