# Generated by Django 4.1.2 on 2022-10-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiconapi', '0005_reservation_created_at_reservation_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='completed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.IntegerField(choices=[(0, 'inprocessing'), (1, 'completed'), (-1, 'desabled')], default=0),
        ),
    ]
